import type { AspectSpec } from '@/types';

export const aspectRegistry: AspectSpec[] = [
  {
    key: 'workflow.phase',
    name: 'Workflow Phase',
    description: 'Named phase segment that groups a contiguous span of steps into a research-readable stage.',
    allowedTargetTypes: ['span'],
    valueType: 'text',
    version: '1.0.0',
    active: true,
  },
  {
    key: 'correctness.task_understanding',
    name: 'Task Understanding',
    description: 'Whether the step/trajectory correctly captures user intent and constraints.',
    allowedTargetTypes: ['step', 'span', 'round', 'trajectory'],
    valueType: 'categorical',
    valueConstraints: { options: ['strong', 'adequate', 'weak'] },
    version: '1.0.0',
    active: true,
  },
  {
    key: 'planning.decomposition_quality',
    name: 'Decomposition Quality',
    description: 'Quality of plan decomposition into executable subtasks.',
    allowedTargetTypes: ['step', 'span', 'round', 'trajectory'],
    valueType: 'categorical',
    valueConstraints: { options: ['good', 'ok', 'bad'] },
    version: '1.0.0',
    active: true,
  },
  {
    key: 'factuality.grounding',
    name: 'Factual Grounding',
    description: 'Whether claims are grounded in evidence from context or tools.',
    allowedTargetTypes: ['step', 'span', 'round', 'trajectory'],
    valueType: 'categorical',
    valueConstraints: { options: ['strong', 'partial', 'weak'] },
    version: '1.0.0',
    active: true,
  },
  {
    key: 'tool.usefulness',
    name: 'Tool Usefulness',
    description: 'Whether a tool action materially helped the trajectory advance toward the task.',
    allowedTargetTypes: ['step', 'span', 'round', 'trajectory'],
    valueType: 'categorical',
    valueConstraints: { options: ['effective', 'mixed', 'ineffective'] },
    version: '1.0.0',
    active: true,
  },
  {
    key: 'progression.execution',
    name: 'Execution Progression',
    description: 'Whether the current step/span advances, stalls, or regresses task execution.',
    allowedTargetTypes: ['step', 'span', 'round', 'trajectory'],
    valueType: 'categorical',
    valueConstraints: { options: ['advance', 'stall', 'regress'] },
    version: '1.0.0',
    active: true,
  },
  {
    key: 'outcome.quality',
    name: 'Outcome Quality',
    description: 'Overall quality of the produced outcome for a step or full trajectory.',
    allowedTargetTypes: ['step', 'span', 'round', 'trajectory'],
    valueType: 'categorical',
    valueConstraints: { options: ['good', 'partial', 'poor'] },
    version: '1.0.0',
    active: true,
  },
  {
    key: 'request.task_type',
    name: 'Request Task Type',
    description: 'Primary task category expressed by the user at the dialogue-round level.',
    allowedTargetTypes: ['round'],
    valueType: 'categorical',
    valueConstraints: {
      options: ['bug_fix', 'feature', 'refactor', 'configuration', 'analysis', 'validation', 'mixed'],
    },
    guideline:
      'Prefer the dominant user ask for the round. Use mixed only when two or more categories are equally central.',
    version: '1.0.0',
    active: true,
  },
  {
    key: 'request.intent_type',
    name: 'Request Intent Type',
    description: 'Interaction intent conveyed by the user in the current round.',
    allowedTargetTypes: ['round'],
    valueType: 'set',
    valueConstraints: {
      options: ['new_requirement', 'follow_up', 'correction', 'dissatisfaction', 'continue', 'interruption', 'constraint_emphasis'],
    },
    guideline:
      'This field is multi-label. Capture why the user is speaking now, not what the agent eventually did.',
    version: '1.0.0',
    active: true,
  },
];
